city = ['bones', 'bag', 'stok', 'dog', 'cat']
city.reverse()
print(city)
city.reverse()
print(city)
print(sorted(city))
print(city)
sorted(city, reverse=True)
print(sorted(city, reverse=True))
print(city)
city.reverse()
print(city)
city.reverse()
print(city)
city.sort()
print(city)
city.sort(reverse=True)
print(city)
